// copilot-companion state layer (v6.1).
//
// Everything user-visible outside of transient process memory lives as a
// flat file under ~/.claude/copilot-companion/:
//
//   default-model                     — optional one-line model id
//   threads/<thread-name>.sid         — persisted Copilot session ids
//
// Writes are atomic (tmp + rename) with 0600 perms so concurrent reads never
// observe a half-written file and nothing leaks across local accounts.
//
// Session tracking and pause gating were removed in v6.1: the bridge is now
// spawned inline per subagent invocation, so there is no separate activation
// lifecycle to track.

import { readFileSync, writeFileSync, unlinkSync,
         readdirSync, mkdirSync, renameSync, chmodSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { homedir } from 'node:os';
import { randomBytes } from 'node:crypto';

export const BASE_DIR     = process.env.COPILOT_COMPANION_HOME
  || join(homedir(), '.claude', 'copilot-companion');
export const MODEL_FILE   = join(BASE_DIR, 'default-model');
export const THREADS_DIR  = join(BASE_DIR, 'threads');

export const DEFAULT_MODEL = 'gpt-5.5';

// Centralised allow-list — the authoritative list lived only in docs before.
export const ALLOWED_MODELS = new Set([
  'claude-opus-4.7',
  'claude-opus-4.6',
  'claude-opus-4.5',
  'claude-sonnet-4.6',
  'claude-sonnet-4.5',
  'claude-sonnet-4',
  'claude-haiku-4.5',
  'gpt-5.5',
  'gpt-5.4',
  'gpt-5.3-codex',
  'gpt-5.2-codex',
  'gpt-5.2',
  'gpt-5.4-mini',
  'gpt-5-mini',
  'gpt-4.1',
]);

function ensureDir(dir) {
  mkdirSync(dir, { recursive: true, mode: 0o700 });
}

function atomicWrite(path, content) {
  // Write the tmp file in the same directory as the target so the rename is
  // always intra-filesystem and atomic. Using os.tmpdir() races when /tmp is
  // on a different volume than $HOME — node falls back to copy+unlink,
  // opening a TOCTOU window where a partial-content file is briefly readable
  // at the target path.
  const dir = dirname(path);
  ensureDir(dir);
  const tmp = join(dir, `.copilot-${randomBytes(6).toString('hex')}.tmp`);
  writeFileSync(tmp, content, { mode: 0o600 });
  try { chmodSync(tmp, 0o600); } catch {}
  renameSync(tmp, path);
  try { chmodSync(path, 0o600); } catch {}
}

function readFileSafe(path) {
  try { return readFileSync(path, 'utf8'); } catch { return null; }
}

// ------------------------------------------------------ default-model
//
// Single-line file. Empty or missing → `DEFAULT_MODEL` fallback.
// Callers get back { model, source } so they can explain where the value
// came from when something goes wrong.

export function readDefaultModel() {
  const raw = readFileSafe(MODEL_FILE);
  if (raw == null) return { model: DEFAULT_MODEL, source: 'fallback' };
  const model = raw.trim();
  if (!model) return { model: DEFAULT_MODEL, source: 'fallback' };
  return { model, source: 'config' };
}

export function writeDefaultModel(id) {
  const clean = String(id ?? '').trim();
  if (!clean) throw new Error('writeDefaultModel: empty id');
  atomicWrite(MODEL_FILE, clean + '\n');
}

export function clearDefaultModel() {
  try { unlinkSync(MODEL_FILE); } catch {}
}

export function isModelAllowed(id) {
  return ALLOWED_MODELS.has(String(id || '').trim());
}

// --------------------------------------------------------- threads/
//
// `name` is a short slug picked by the caller (or auto-generated by the
// bridge as `companion-<jobId>`). Each thread maps to a single Copilot ACP
// session id, captured on first send and reused on subsequent sends via
// --session=<sid>.

function threadPath(name) {
  if (!name || !/^[a-zA-Z0-9._-]+$/.test(name))
    throw new Error('invalid thread name (allowed: [a-zA-Z0-9._-])');
  return join(THREADS_DIR, `${name}.sid`);
}

// Thread sid is read on every `send` that uses a thread (hot path, once per
// delegation) and written exactly once per Copilot session rotation (rare).
// An in-memory cache eliminates the read syscall in the common case where a
// long-lived thread reuses the same sid for hundreds of turns. Cache is
// invalidated on writeThreadSid / clearThread.
const threadSidCache = new Map();

export function readThreadSid(name) {
  if (threadSidCache.has(name)) return threadSidCache.get(name);
  const raw = readFileSafe(threadPath(name));
  const sid = raw ? raw.trim() || null : null;
  threadSidCache.set(name, sid);
  return sid;
}

export function writeThreadSid(name, sid) {
  const clean = String(sid ?? '').trim();
  if (!clean) throw new Error('writeThreadSid: empty sid');
  atomicWrite(threadPath(name), clean + '\n');
  threadSidCache.set(name, clean);
}

export function clearThread(name) {
  try { unlinkSync(threadPath(name)); } catch {}
  threadSidCache.delete(name);
}

export function listThreads() {
  ensureDir(THREADS_DIR);
  return readdirSync(THREADS_DIR)
    .filter((f) => f.endsWith('.sid'))
    .map((f) => f.slice(0, -4));
}

export function clearAllThreads() {
  for (const name of listThreads()) clearThread(name);
}
